import type { DomainDefinition, Question } from "./koss43.types";

export const DOMAIN_DEFINITIONS: DomainDefinition[] = [
  {
    id: "physicalEnvironment",
    label: "물리적 환경",
    shortLabel: "물리환경",
    itemIds: [1, 2, 3],
    meaning: "점수가 높을수록 물리적 환경이 상대적으로 나쁘다.",
  },
  {
    id: "jobDemand",
    label: "직무 요구",
    shortLabel: "직무요구",
    itemIds: [4, 5, 6, 7, 8, 9, 10, 11],
    meaning: "점수가 높을수록 직무 요구도가 상대적으로 높다.",
  },
  {
    id: "jobControlDeficit",
    label: "직무 자율성 결여",
    shortLabel: "직무자율",
    itemIds: [12, 13, 14, 15, 16],
    meaning: "점수가 높을수록 직무 자율성이 상대적으로 낮다.",
  },
  {
    id: "interpersonalConflict",
    label: "관계 갈등",
    shortLabel: "관계갈등",
    itemIds: [17, 18, 19, 20],
    meaning: "점수가 높을수록 관계 갈등이 상대적으로 크다.",
  },
  {
    id: "jobInsecurity",
    label: "직무 불안정",
    shortLabel: "직무불안정",
    itemIds: [21, 22, 23, 24, 25, 26],
    meaning: "점수가 높을수록 직업이 상대적으로 불안정하다.",
  },
  {
    id: "organizationalSystem",
    label: "조직 체계",
    shortLabel: "조직체계",
    itemIds: [27, 28, 29, 30, 31, 32, 33],
    meaning: "점수가 높을수록 조직이 상대적으로 체계적이지 않다.",
  },
  {
    id: "lackOfReward",
    label: "보상 부적절",
    shortLabel: "보상부적절",
    itemIds: [34, 35, 36, 37, 38, 39],
    meaning: "점수가 높을수록 보상체계가 상대적으로 부적절하다.",
  },
  {
    id: "occupationalClimate",
    label: "직장 문화",
    shortLabel: "직장문화",
    itemIds: [40, 41, 42, 43],
    meaning: "점수가 높을수록 직장문화에 대한 스트레스가 상대적으로 높다.",
  },
];

export const KOSS43_QUESTIONS: Question[] = [
  {
    id: 1,
    domainId: "physicalEnvironment",
    text: "근무 장소가 깨끗하고 쾌적하다.",
    reverse: true,
  },
  {
    id: 2,
    domainId: "physicalEnvironment",
    text: "내 일은 위험하여 사고를 당할 가능성이 있다.",
    reverse: false,
  },
  {
    id: 3,
    domainId: "physicalEnvironment",
    text: "나는 불편한 자세로 오랫동안 일을 해야 한다.",
    reverse: false,
  },
  {
    id: 4,
    domainId: "jobDemand",
    text: "나는 일이 많아 항상 시간에 쫓기며 일한다.",
    reverse: false,
  },
  {
    id: 5,
    domainId: "jobDemand",
    text: "현재 하던 일을 끝내기 전에 다른 일을 하도록 지시받는다",
    reverse: false,
  },
  {
    id: 6,
    domainId: "jobDemand",
    text: "업무량이 현저하게 증가하였다.",
    reverse: false,
  },
  {
    id: 7,
    domainId: "jobDemand",
    text: "나는 동료나 부하직원을 돌보고 책임져야 할 부담을 안고 있다.",
    reverse: false,
  },
  {
    id: 8,
    domainId: "jobDemand",
    text: "내 업무는 장시간 동안 집중력이 요구된다.",
    reverse: false,
  },
  {
    id: 9,
    domainId: "jobDemand",
    text: "업무 수행 중에 충분한 휴식(짬)이 주어진다.",
    reverse: true,
  },
  {
    id: 10,
    domainId: "jobDemand",
    text: "일이 많아서 직장과 가정에 다 잘하기가 힘들다.",
    reverse: false,
  },
  {
    id: 11,
    domainId: "jobDemand",
    text: "여러 가지 일을 동시에 해야 한다.",
    reverse: false,
  },
  {
    id: 12,
    domainId: "jobControlDeficit",
    text: "내 업무는 창의력을 필요로 한다.",
    reverse: true,
  },
  {
    id: 13,
    domainId: "jobControlDeficit",
    text: "업무 관련 사항(업무의 일정, 업무량, 회의 시간 등)이 예고 없이 갑작스럽게 정해지거나 바뀐다.",
    reverse: false,
  },
  {
    id: 14,
    domainId: "jobControlDeficit",
    text: "내 업무를 수행하기 위해서는 높은 수준의 기술이나 지식이 필요하다.",
    reverse: true,
  },
  {
    id: 15,
    domainId: "jobControlDeficit",
    text: "작업시간, 업무 수행 과정에서 내가 스스로 결정할 권한이 주어진다.",
    reverse: true,
  },
  {
    id: 16,
    domainId: "jobControlDeficit",
    text: "나의 업무량과 작업 스케줄을 스스로 조절할 수 있다.",
    reverse: true,
  },
  {
    id: 17,
    domainId: "interpersonalConflict",
    text: "나의 상사는 업무를 수행하는 데 도움을 준다.",
    reverse: true,
  },
  {
    id: 18,
    domainId: "interpersonalConflict",
    text: "나의 동료는 업무를 수행하는 데 도움을 준다.",
    reverse: true,
  },
  {
    id: 19,
    domainId: "interpersonalConflict",
    text: "직장에서 내가 힘들 때 내가 힘들다는 것을 알아주고 이해해 주는 사람이 있다.",
    reverse: true,
  },
  {
    id: 20,
    domainId: "interpersonalConflict",
    text: "직장생활의 고충을 함께 나눌 동료가 있다.",
    reverse: true,
  },
  {
    id: 21,
    domainId: "jobInsecurity",
    text: "지금의 직장을 옮겨도 나에게 적합한 새로운 일을 쉽게 찾을 수 있다.",
    reverse: true,
  },
  {
    id: 22,
    domainId: "jobInsecurity",
    text: "현재의 직장을 그만두어도 현재 수준만큼의 직업(직장)을 쉽게 구할 수 있다.",
    reverse: true,
  },
  {
    id: 23,
    domainId: "jobInsecurity",
    text: "직장 사정이 불안하여 미래가 불확실하다.",
    reverse: false,
  },
  {
    id: 24,
    domainId: "jobInsecurity",
    text: "나의 직업은 실직하거나 해고당할 염려가 없다.",
    reverse: true,
  },
  {
    id: 25,
    domainId: "jobInsecurity",
    text: "앞으로 2년 동안 현재의 내 직업을 잃을 가능성이 있다.",
    reverse: false,
  },
  {
    id: 26,
    domainId: "jobInsecurity",
    text: "나의 근무조건이나 상황에 바람직하지 못한 변화(예, 구조 조정)가 있었거나 있을 것으로 예상된다.",
    reverse: false,
  },
  {
    id: 27,
    domainId: "organizationalSystem",
    text: "우리 직장은 근무 평가, 인사제도(예, 승진, 부서 배치) 등의 정책 결정 과정이 공정하고 합리적이다.",
    reverse: true,
  },
  {
    id: 28,
    domainId: "organizationalSystem",
    text: "업무 수행에 필요한 인원, 공간, 시설, 장비, 훈련 등의 지원이 잘 이루어지고 있다.",
    reverse: true,
  },
  {
    id: 29,
    domainId: "organizationalSystem",
    text: "우리 부서와 타 부서 간에는 마찰이 없고 업무 협조가 잘 이루어진다.",
    reverse: true,
  },
  {
    id: 30,
    domainId: "organizationalSystem",
    text: "근로자, 간부, 경영주 모두가 직장을 위해 한마음으로 일을 한다.",
    reverse: true,
  },
  {
    id: 31,
    domainId: "organizationalSystem",
    text: "업무 수행 과정에 나의 생각을 반영할 수 있는 기회와 통로가 있다.",
    reverse: true,
  },
  {
    id: 32,
    domainId: "organizationalSystem",
    text: "나의 경력 개발과 승진은 무난히 잘 될 것으로 예상한다.",
    reverse: true,
  },
  {
    id: 33,
    domainId: "organizationalSystem",
    text: "나의 현재 직위는 나의 교육 및 경력에 비추어 볼 때 적절하다.",
    reverse: true,
  },
  {
    id: 34,
    domainId: "lackOfReward",
    text: "나의 직업은 내가 평소 기대했던 것에 미치지 못한다.",
    reverse: false,
  },
  {
    id: 35,
    domainId: "lackOfReward",
    text: "나의 모든 노력과 업적을 고려할 때 내 봉급/수입은 적절하다.",
    reverse: true,
  },
  {
    id: 36,
    domainId: "lackOfReward",
    text: "내가 쏟는 노력과 업적을 고려할 때, 나는 직장에서 제대로 존중과 신임을 받고 있다.",
    reverse: true,
  },
  {
    id: 37,
    domainId: "lackOfReward",
    text: "나는 지금 하는 일에 흥미를 느낀다.",
    reverse: true,
  },
  {
    id: 38,
    domainId: "lackOfReward",
    text: "내 사정이 앞으로 더 좋아질 것을 생각하면 힘든 줄 모르고 일하게 된다.",
    reverse: true,
  },
  {
    id: 39,
    domainId: "lackOfReward",
    text: "나의 능력을 개발하고 발휘할 수 있는 기회가 주어진다.",
    reverse: true,
  },
  {
    id: 40,
    domainId: "occupationalClimate",
    text: "회식 자리가 불편하다.",
    reverse: false,
  },
  {
    id: 41,
    domainId: "occupationalClimate",
    text: "나는 기준이나 일관성이 없는 상태로 업무지시를 받는다.",
    reverse: false,
  },
  {
    id: 42,
    domainId: "occupationalClimate",
    text: "직장의 분위기가 권위적이고 수직적이다.",
    reverse: false,
  },
  {
    id: 43,
    domainId: "occupationalClimate",
    text: "남성, 여성이라는 성적인 차이 때문에 불이익을 받는다.",
    reverse: false,
  },
];

export const KOSS_SOURCE =
  "KOSHA GUIDE E-G-2-2025 「직무스트레스로 인한 건강장해 예방 기술지원규정」 <부록 1> 한국인 직무스트레스 요인 평가도구";

export const ANSWER_LABELS = [
  { value: 1, label: "전혀 그렇지 않다" },
  { value: 2, label: "그렇지 않다" },
  { value: 3, label: "그렇다" },
  { value: 4, label: "매우 그렇다" },
] as const;
